name: Frontend V2 Pull Request Workflow

on:
  pull_request:
    branches: [ "main" ]

jobs:
  linter-frontend-v2:
    runs-on: ubuntu-latest
    env:
      TZ: 'America/Sao_Paulo'

    steps:
      - name: ğŸ”¥ Configuring checkout
        uses: actions/checkout@v4

      - name: ğŸ“„ Making .env file
        run: |
          echo "${{ secrets.ENV_MFP_FRONTEND_V2 }}" > resources/frontend-v2/.env

      - name: ğŸ› ï¸ Installing Node dependencies
        run: cd resources/frontend-v2 && npm install

      - name: ğŸ” Executing linter
        run: cd resources/frontend-v2 && npm run lint


  test-vitest-frontend-v2:
    runs-on: ubuntu-latest
    env:
      TZ: 'America/Sao_Paulo'

    steps:
      - name: ğŸ”¥ Configuring checkout
        uses: actions/checkout@v4

      - name: ğŸ“„ Making .env file
        run: |
          echo "${{ secrets.ENV_MFP_FRONTEND_V2 }}" > resources/frontend-v2/.env

      - name: ğŸ› ï¸ Installing Node dependencies
        run: cd resources/frontend-v2 && npm install

      - name: ğŸ§ª Executing Vitest tests
        run: cd resources/frontend-v2 && npm run test:unit

  test-build-frontend-v2:
    runs-on: ubuntu-latest
    env:
      TZ: 'America/Sao_Paulo'

    steps:
      - name: ğŸ”¥ Configuring checkout
        uses: actions/checkout@v4

      - name: ğŸ“„ Making .env file
        run: |
          echo "${{ secrets.ENV_MFP_FRONTEND_V2 }}" > resources/frontend-v2/.env

      - name: ğŸ› ï¸ Installing Node dependencies
        run: cd resources/frontend-v2 && npm install

      - name: ğŸ“¦ Testing building application
        run: cd resources/frontend-v2 && npm run build