name: Frontend V2 Deploy Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-frontend-v2-private-server:
    runs-on: ubuntu-latest
    env:
      TZ: 'America/Sao_Paulo'

    steps:
      - name: ğŸ”¥ Configuring checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: ğŸ“„ Making .env file
        run: |
          echo "${{ secrets.ENV_MFP_FRONTEND_V2 }}" > resources/frontend-v2/.env

      - name: ğŸ› ï¸ Installing Node dependencies
        run: cd resources/frontend-v2 && npm install

      - name: ğŸ“¦ï¸ Building application
        run: cd resources/frontend-v2 && npm run build

      - name: ğŸ“‚ Upload files to private server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_ADDRESS }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/build-ionic/
          server-dir: ./projects/my-finances-planner/public/build-ionic/
          dangerous-clean-slate: true

  deploy-frontend-v2-demo-server:
    runs-on: ubuntu-latest
    env:
      TZ: 'America/Sao_Paulo'

    steps:
      - name: ğŸ”¥ Configuring checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: ğŸ“„ Making .env file
        run: |
          echo "${{ secrets.ENV_MFP_FRONTEND_V2_DEMO }}" > resources/frontend-v2/.env

      - name: ğŸ› ï¸ Installing Node dependencies
        run: cd resources/frontend-v2 && npm install

      - name: ğŸ“¦ï¸ Building application
        run: cd resources/frontend-v2 && npm run build

      - name: ğŸ“‚ Upload files to demo server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_ADDRESS }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/build-ionic/
          server-dir: ./projects/my-finances-planner-demo/public/build-ionic/
          dangerous-clean-slate: true