name: Frontend V1 Pull Request Workflow

on:
  pull_request:
    branches: [ "main" ]

jobs:
  linter-frontend-v1:
    runs-on: ubuntu-latest
    env:
      TZ: 'America/Sao_Paulo'

    steps:
      - name: ğŸ”¥ Configuring checkout
        uses: actions/checkout@v4

      - name: ğŸ“„ Making .env file
        run: |
          echo "${{ secrets.ENV_MFP_PERSONAL }}" > .env

      - name: ğŸ› ï¸ Installing Node dependencies
        run: npm install

      - name: ğŸ” Executing linter
        run: npm run analyze:eslint


  test-vitest-frontend-v1:
    runs-on: ubuntu-latest
    env:
      TZ: 'America/Sao_Paulo'

    steps:
      - name: ğŸ”¥ Configuring checkout
        uses: actions/checkout@v4

      - name: ğŸ“„ Making .env file
        run: |
          echo "${{ secrets.ENV_MFP_PERSONAL }}" > .env

      - name: ğŸ› ï¸ Installing Node dependencies
        run: npm install

      - name: ğŸ§ª Executing Vitest tests
        run: LARAVEL_BYPASS_ENV_CHECK=1 npm run test:run

  test-build-frontend-v1:
    runs-on: ubuntu-latest
    env:
      TZ: 'America/Sao_Paulo'

    steps:
      - name: ğŸ”¥ Configuring checkout
        uses: actions/checkout@v4

      - name: ğŸ“„ Making .env file
        run: |
          echo "${{ secrets.ENV_MFP_PERSONAL }}" > .env

      - name: ğŸ› ï¸ Installing Node dependencies
        run: npm install

      - name: ğŸ“¦ Testing building application
        run: npm run build